### create report

POST http://localhost:3000/report
Content-Type: application/json

{
    "price": 100,
    "make": "Toyota",
    "model": "Corolla",
    "year": 2015,
    "lng": 80,
    "lat": 80
}

### Approve report

PATCH http://localhost:3000/report/45
Content-Type: application/json

{
    "approved": true
}
